 server:
#  ssl:
#    key-store: classpath:${ENVIRONMENT:dev}.pfx
#    key-store-password: ${KEY_STORE_PASSWORD:wso2carbon}
#    key-store-type: pkcs12
#    key-password: ${KEY_STORE_PASSWORD:wso2carbon}
  servlet:
    context-path: /
  port: 8443
  error:
    whitelabel:
      enabled: false


 spring:
   zipkin:
     base-url: ${SPRING_ZIPKIN_BASE_URL:http://${HOST_IP_ADDRESS:localhost}:9411/}
   config:
     import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://${HOST_IP_ADDRESS:localhost}:9296}
   application:
     name: API-GATEWAY
   profiles:
     active: ${SPRING_PROFILES_ACTIVE:dev}
   cloud:
     gateway:
       default-filters:
         - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
       globalcors:
         add-to-simple-url-handler-mapping: true
         cors-configurations:
           '[/**]':
             allowed-origins: "${CLIENT_HOST:http://${HOST_IP_ADDRESS:localhost}:4200}"
             allowed-headers: "*"
             exposed-headers: "*"
             allow-credentials: true
             allowed-methods:
               - GET
               - POST
               - PUT
               - DELETE
               - PATCH
               - OPTIONS
       routes:
         - id: TENANT-SERVICE
           uri: lb://TENANT-SERVICE
           predicates:
             - Path=/tenant-service/**
         - id: ORDER-SERVICE
           uri: lb://ORDER-SERVICE
           predicates:
             - Path=/order-service/**
         - id: PAYMENT-SERVICE
           uri: lb://PAYMENT-SERVICE
           predicates:
             - Path=/payment-service/**
         - id: PRODUCT-SERVICE
           uri: lb://PRODUCT-SERVICE
           predicates:
             - Path=/product-service/**
         - id: SHIPPING-SERVICE
           uri: lb://SHIPPING-SERVICE
           predicates:
             - Path=/shipping-service/**
         - id: USER-SERVICE
           uri: lb://USER-SERVICE
           predicates:
             - Path=/user-service/**
         - id: FAVOURITE-SERVICE
           uri: lb://FAVOURITE-SERVICE
           predicates:
             - Path=/favourite-service/**
         - id: SYSTEM-SERVICE
           uri: lb://SYSTEM-SERVICE
           predicates:
             - Path=/system-service/**
         - id: INTEGRATION-SERVICE
           uri: lb://INTEGRATION-SERVICE
           predicates:
             - Path=/integration-service/**
         - id: INVENTORY-SERVICE
           uri: lb://INVENTORY-SERVICE
           predicates:
             - Path=/inventory-service/**
         - id: REPORT-SERVICE
           uri: lb://REPORT-SERVICE
           predicates:
             - Path=/report-service/**
         - id: PROXY-CLIENT
           uri: lb://PROXY-CLIENT
           predicates:
             - Path=/app/**

 resilience4j:
   circuitbreaker:
     instances:
       apiGateway:
         register-health-indicator: true
         event-consumer-buffer-size: 10
         automatic-transition-from-open-to-half-open-enabled: true
         failure-rate-threshold: 50
         minimum-number-of-calls: 5
         permitted-number-of-calls-in-half-open-state: 3
         sliding-window-size: 10
         wait-duration-in-open-state: 5s
         sliding-window-type: COUNT_BASED

 management:
   health:
     circuitbreakers:
       enabled: true
   endpoint:
     health:
       show-details: always

 eureka:
   client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
       defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://${HOST_IP_ADDRESS:localhost}:8761/eureka}
   instance:
     prefer-ip-address: true
     ip-address: ${HOST_IP_ADDRESS:localhost}