
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:172.16.3.12}:${DB_PORT:51173}/pos_web_app_db
    username: postgres
    password: ${DB_PASSWORD:HrWL(f#vXnrIWNkL}
#  session:
#    store-type: redis
#    redis:
#    namespace: "spring:session:dbiz"

  jpa:
    show-sql: false
    hibernate:
     ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        format_sql: true
        default_schema: pos
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#        envers:
#          audit_strategy: com.dbiz.app.userservice.config.audit.CustomAuditStrategy


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://${HOST_IP_ADDRESS:localhost}:8761/eureka}
#  instance:
#    ip-address: ${HOST_IP_ADDRESS:localhost}